Relax type bounds
logos-co/Overwatch pull request #17
Opened 2023-01-11 10:12 UTC by Zeegomo

2023-01-11 10:35 UTC, danielSanchezQ approved these changes

2023-01-11 10:35 UTC, danielSanchezQ commented on overwatch-rs/src/services/state.rs
> +unsafe impl<T> Send for NoOperator<T> {}
Wasnt this changed already? 🤔

2023-01-11 11:03 UTC, Zeegomo commented on overwatch-rs/src/services/state.rs
> +unsafe impl<T> Send for NoOperator<T> {}
ops, git history got confused

2023-01-12 09:24 UTC, danielSanchezQ approved these changes

2023-01-12 09:26 UTC, danielSanchezQ requested changes

2023-01-12 09:26 UTC, danielSanchezQ commented on overwatch-rs/src/services/relay.rs
> +
This is duplicated now, as it is in utils as well.

2023-01-17 13:03 UTC, danielSanchezQ approved these changes

2023-01-17 13:45 UTC, merged